// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZRuhHqR94Eq_U6bySI6-XynP-5ETXTuE',
    appId: '1:1039167635541:web:691693265e9d55fc8814dc',
    messagingSenderId: '1039167635541',
    projectId: 'uno-chat-2024',
    authDomain: 'uno-chat-2024.firebaseapp.com',
    storageBucket: 'uno-chat-2024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-gtWiGu9fWj_FcFF8tTrrL8OjiqZ8_z0',
    appId: '1:1039167635541:ios:39329ef520e3b6538814dc',
    messagingSenderId: '1039167635541',
    projectId: 'uno-chat-2024',
    storageBucket: 'uno-chat-2024.firebasestorage.app',
    iosBundleId: 'com.example.unoChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-gtWiGu9fWj_FcFF8tTrrL8OjiqZ8_z0',
    appId: '1:1039167635541:ios:39329ef520e3b6538814dc',
    messagingSenderId: '1039167635541',
    projectId: 'uno-chat-2024',
    storageBucket: 'uno-chat-2024.firebasestorage.app',
    iosBundleId: 'com.example.unoChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZRuhHqR94Eq_U6bySI6-XynP-5ETXTuE',
    appId: '1:1039167635541:web:222e8decfb2b80da8814dc',
    messagingSenderId: '1039167635541',
    projectId: 'uno-chat-2024',
    authDomain: 'uno-chat-2024.firebaseapp.com',
    storageBucket: 'uno-chat-2024.firebasestorage.app',
  );
}
